title: Reading Notes
description: Showcasing my progress during the TechEducator Full-Stack MERN Bootcamp. Explore through the 'Class Content' or read about me below!
url: https://cailumleyshon.github.io
theme: jekyll-theme-minimal
plugins:
  - jekyll-seo-tag
  - jekyll-toc
